name: node-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID}}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEYBASE64 }}
        export_default_credentials: true
    
   
        
     # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker    
        
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud services enable containerregistry.googleapis.com 
        gcloud services enable run.googleapis.com
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}/node-image
        gcloud config set run/region us-central1
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated 
    - name: delete unused image from cloud registry
      run: |
        gcloud container images list-tags gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-image --filter='-tags:*' --format="get(digest)" --limit=10
        gcloud container images delete gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-image@DIGEST --quiet



