name: node-deploy
on:
  push:
    branches:
      - main
      - staging
      - production
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
      if: github.ref == 'refs/heads/production'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID}}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.PRODUCTION_GCP_SA_KEYBASE64 }}
        export_default_credentials: true
        
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
      if: github.ref == 'refs/heads/staging'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID}}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEYBASE64 }}
        export_default_credentials: true  
    
   
        
     # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker    
        
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud services enable containerregistry.googleapis.com 
        gcloud services enable run.googleapis.com
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    - name: Build image for staging
      if: github.ref == 'refs/heads/staging'
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}/staging
        gcloud config set run/region us-central1


    - name: Build image for production
      if: github.ref == 'refs/heads/production'
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PRODUCTION_GCP_APPLICATION }}/production
        gcloud config set run/region us-central1    
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy staging
      if: github.ref == 'refs/heads/staging'
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}/staging:latest \
        --platform managed \
        --allow-unauthenticated 

    - name: Deploy production
      if: github.ref == 'refs/heads/production'
      run: |
        gcloud run deploy ${{ secrets.PRODUCTION_GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.PRODUCTION_GCP_APPLICATION }}/production:latest \
        --platform managed \
        --allow-unauthenticated     

    - name: remove image     
      if: github.ref == 'refs/heads/staging'
      run:
        gcloud container images list-tags gcr.io/node-app-demo-354208/cloud-run-demo/staging --filter='-tags:*' --format='get(digest)' --limit=unlimited | awk '{print "gcr.io/node-app-demo-354208/cloud-run-demo/staging@" $1}' | xargs gcloud container images delete --quiet

    - name: remove image     
      if: github.ref == 'refs/heads/production'
      run:
        gcloud container images list-tags gcr.io/node-app-demo-354208/node-app-production/production --filter='-tags:*' --format='get(digest)' --limit=unlimited | awk '{print "gcr.io/node-app-demo-354208/node-app-production/production@" $1}' | xargs gcloud container images delete --quiet    







